#Use an official python runtime as a parent image
FROM python:3.8-slim

#set the working directory
WORKDIR /app

#copy the current directory contents into the container at /app
COPY . /app

#install any needed packages specifies in requirements.txt
RUN pip instll --no-chache-dir -r requirements.txt

#Make port 5000 available to the work=ld outside this container
EXPOSE 5000

#Define environment vriable 
ENV FLASK_APP=app.py

# Run the Flask app
CMD  ["flask", "run", "--host=0.0.0.0"]